# Generated by Django 2.2.13 on 2020-06-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=48)),
                ('account', models.CharField(max_length=48, unique=True)),
                ('passwd', models.CharField(max_length=128)),
                ('status', models.IntegerField(default=0)),
                ('role', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
